export const ActionTypes = {
    //Authentication constants
    IS_USER_AUTHENTICATE: "IS_USER_AUTHENTICATE",
    AUTH_TOKEN: "AUTH_TOKEN",
    USER_ID: "USER_ID",

    //User Modules constants
    AUTHENTICATED_USER_MODULES: "AUTHENTICATED_USER_MODULES",
    USER_MENU: "USER_MENU" ,

    //OPD Registration
    SELECTED_DOCTOR: "SELECTED_DOCTOR",
    REMOVE_SELECTED_DOCTOR: "REMOVE_SELECTED_DOCTOR",
    SET_PATIENT_DETAIL: "SET_PATIENT_DETAIL",
    SET_OPD_DISCOUNT_DATA: "SET_OPD_DISCOUNT_DATA",
    SET_BILLING_DATA: "SET_BILLING_DATA",
    CLEAR_SELECTED_DOCTOR_DATA: "CLEAR_SELECTED_DOCTOR_DATA",
    CLEAR_BILLING_DATA: "CLEAR_BILLING_DATA",

    //e-opd
    SET_DIAGNOSIS_INFO: "SET_DIAGNOSIS_INFO"
}